# Generated by Django 3.2.15 on 2022-09-06 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, default='../default-post_oi2vmt', upload_to='images/')),
                ('content', models.TextField(max_length=1600)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Movies', 'Movies'), ('Vehicles', 'Vehicles'), ('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Other,', 'Other')], default='Other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
