# Generated by Django 3.2.15 on 2022-09-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Very bad'), (2, 'bad'), (3, 'good'), (4, 'Very good'), (1, 'Extremely good')], default=3),
        ),
    ]
